//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalLogDBContainer : DbContext
    {
        public CarRentalLogDBContainer()
            : base("name=CarRentalLogDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<crLogDriver> crLogDrivers { get; set; }
        public virtual DbSet<crLogUnit> crLogUnits { get; set; }
        public virtual DbSet<crLogCompany> crLogCompanies { get; set; }
        public virtual DbSet<crLogTrip> crLogTrips { get; set; }
        public virtual DbSet<crLogCashRelease> crLogCashReleases { get; set; }
        public virtual DbSet<crLogClosing> crLogClosings { get; set; }
        public virtual DbSet<crLogFuel> crLogFuels { get; set; }
        public virtual DbSet<crLogOdo> crLogOdoes { get; set; }
        public virtual DbSet<crCashReqStatus> crCashReqStatus { get; set; }
        public virtual DbSet<crLogFuelStatus> crLogFuelStatus { get; set; }
        public virtual DbSet<crLogCashStatus> crLogCashStatus { get; set; }
        public virtual DbSet<crLogType> crLogTypes { get; set; }
        public virtual DbSet<crRptUnitExpense> crRptUnitExpenses { get; set; }
        public virtual DbSet<CrRptUnit> CrRptUnits { get; set; }
        public virtual DbSet<crLogPaymentType> crLogPaymentTypes { get; set; }
        public virtual DbSet<crLogCashType> crLogCashTypes { get; set; }
        public virtual DbSet<crLogPassenger> crLogPassengers { get; set; }
        public virtual DbSet<crLogPassStatus> crLogPassStatus { get; set; }
        public virtual DbSet<crLogPassengerMaster> crLogPassengerMasters { get; set; }
        public virtual DbSet<crLogPassengerArea> crLogPassengerAreas { get; set; }
        public virtual DbSet<crLogPassRemarks> crLogPassRemarks { get; set; }
        public virtual DbSet<crLogOwner> crLogOwners { get; set; }
        public virtual DbSet<crLogTripJobMain> crLogTripJobMains { get; set; }
    }
}
