//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crLogCashSalary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crLogCashSalary()
        {
            this.crLogCashGroups = new HashSet<crLogCashGroup>();
        }
    
        public int Id { get; set; }
        public string Date { get; set; }
        public int crLogDriverId { get; set; }
        public bool ExcludeOT { get; set; }
    
        public virtual crLogDriver crLogDriver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crLogCashGroup> crLogCashGroups { get; set; }
    }
}
