//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crLogTripJobMain
    {
        public int Id { get; set; }
        public int JobMainId { get; set; }
        public int crLogTripId { get; set; }
    
        public virtual crLogTrip crLogTrip { get; set; }
    }
}
