//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crLogCompanyRate
    {
        public int Id { get; set; }
        public decimal TripRate { get; set; }
        public decimal OTRate { get; set; }
        public int TripHours { get; set; }
        public decimal DriverDailyRate { get; set; }
        public decimal DriverOTRate { get; set; }
        public int crLogCompanyId { get; set; }
    
        public virtual crLogCompany crLogCompany { get; set; }
    }
}
