//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crLogFuel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crLogFuel()
        {
            this.crLogFuelStatus = new HashSet<crLogFuelStatus>();
        }
    
        public int Id { get; set; }
        public System.DateTime dtRequest { get; set; }
        public decimal Amount { get; set; }
        public int crLogUnitId { get; set; }
        public int crLogDriverId { get; set; }
        public System.DateTime dtFillup { get; set; }
        public int odoFillup { get; set; }
        public decimal orAmount { get; set; }
        public int crLogTypeId { get; set; }
    
        public virtual crLogUnit crLogUnit { get; set; }
        public virtual crLogDriver crLogDriver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crLogFuelStatus> crLogFuelStatus { get; set; }
        public virtual crLogType crLogType { get; set; }
    }
}
