//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crLogUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crLogUnit()
        {
            this.crLogTrips = new HashSet<crLogTrip>();
            this.crLogFuels = new HashSet<crLogFuel>();
            this.crLogOdoes = new HashSet<crLogOdo>();
            this.CrRptUnits = new HashSet<CrRptUnit>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Status { get; set; }
        public int crLogOwnerId { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crLogTrip> crLogTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crLogFuel> crLogFuels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crLogOdo> crLogOdoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrRptUnit> CrRptUnits { get; set; }
        public virtual crLogOwner crLogOwner { get; set; }
    }
}
