//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crLogTrip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crLogTrip()
        {
            this.DriverOT = 0m;
            this.crLogPassengers = new HashSet<crLogPassenger>();
            this.crLogTripJobMains = new HashSet<crLogTripJobMain>();
        }
    
        public int Id { get; set; }
        public int crLogDriverId { get; set; }
        public int crLogUnitId { get; set; }
        public int crLogCompanyId { get; set; }
        public System.DateTime DtTrip { get; set; }
        public decimal Rate { get; set; }
        public decimal Expenses { get; set; }
        public decimal DriverFee { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> crLogClosingId { get; set; }
        public decimal Addon { get; set; }
        public Nullable<int> OdoStart { get; set; }
        public Nullable<int> OdoEnd { get; set; }
        public decimal DriverOT { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> TripHours { get; set; }
        public Nullable<decimal> OTRate { get; set; }
        public Nullable<decimal> DriverOTRate { get; set; }
        public Nullable<decimal> AddonOT { get; set; }
        public bool IsFinal { get; set; }
        public bool AllowEdit { get; set; }
        public Nullable<bool> TripTicket { get; set; }
        public Nullable<bool> IncludeOT { get; set; }
    
        public virtual crLogDriver crLogDriver { get; set; }
        public virtual crLogUnit crLogUnit { get; set; }
        public virtual crLogCompany crLogCompany { get; set; }
        public virtual crLogClosing crLogClosing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crLogPassenger> crLogPassengers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crLogTripJobMain> crLogTripJobMains { get; set; }
    }
}
