//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrRptUnit
    {
        public int Id { get; set; }
        public int crRptUnitExpenseId { get; set; }
        public int crLogUnitId { get; set; }
        public int RptSeqNo { get; set; }
    
        public virtual crRptUnitExpense crRptUnitExpense { get; set; }
        public virtual crLogUnit crLogUnit { get; set; }
    }
}
