//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrPersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrPersonel()
        {
            this.HrPerDocs = new HashSet<HrPerDoc>();
            this.HrPerPositions = new HashSet<HrPerPosition>();
            this.HrPerTrainings = new HashSet<HrPerTraining>();
            this.HrPerSkills = new HashSet<HrPerSkill>();
            this.HrDtrs = new HashSet<HrDtr>();
            this.HrSalaries = new HashSet<HrSalary>();
            this.HrPayrolls = new HashSet<HrPayroll>();
            this.HrProfiles = new HashSet<HrProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PassportNo { get; set; }
        public string SSSid { get; set; }
        public string Tin { get; set; }
        public string DriverId { get; set; }
        public string Remarks { get; set; }
        public int HrPersonelStatusId { get; set; }
        public string Philhealth { get; set; }
        public string Pagibig { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPerDoc> HrPerDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPerPosition> HrPerPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPerTraining> HrPerTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPerSkill> HrPerSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrDtr> HrDtrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrSalary> HrSalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPayroll> HrPayrolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrProfile> HrProfiles { get; set; }
        public virtual HrPersonelStatus HrPersonelStatu { get; set; }
    }
}
