//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccntChartAccount
    {
        public int Id { get; set; }
        public int AccntChartId { get; set; }
        public int AccntMainId { get; set; }
    
        public virtual AccntChart AccntChart { get; set; }
        public virtual AccntMain AccntMain { get; set; }
    }
}
