//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccntTrxHist
    {
        public int Id { get; set; }
        public string DtHist { get; set; }
        public int AccntTrxDtlId { get; set; }
        public string HistType { get; set; }
        public string OldData { get; set; }
        public string User { get; set; }
    
        public virtual AccntTrxDtl AccntTrxDtl { get; set; }
    }
}
