//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Areas.Products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmRate
    {
        public int Id { get; set; }
        public string Qty { get; set; }
        public string Rate { get; set; }
        public string DRate { get; set; }
        public int SmProductId { get; set; }
    
        public virtual SmRateUoM SmRateUoM { get; set; }
        public virtual SmProduct SmProduct { get; set; }
    }
}
