//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckerActivity
    {
        public int Id { get; set; }
        public System.DateTime DtActivity { get; set; }
        public string CheckedBy { get; set; }
        public string Remarks { get; set; }
        public int SalesLeadId { get; set; }
        public int CheckerActivityTypeId { get; set; }
    
        public virtual SalesLead SalesLead { get; set; }
        public virtual CheckerActivityType CheckerActivityType { get; set; }
    }
}
