//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntContact
    {
        public int Id { get; set; }
        public int EntCompanyId { get; set; }
        public int SysSetupTypeId { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string TelNo1 { get; set; }
        public string TelNo2 { get; set; }
        public string email { get; set; }
        public string Remarks { get; set; }
    
        public virtual EntBusiness EntCompany { get; set; }
        public virtual SysSetupType SysSetupType { get; set; }
    }
}
