//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntSupportFile
    {
        public int Id { get; set; }
        public int SysFileTypeId { get; set; }
        public int EntCompanyId { get; set; }
        public string UrlPath { get; set; }
    
        public virtual EntBusiness EntCompany { get; set; }
        public virtual SysSetupType SysFileType { get; set; }
    }
}
