//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCarMntRcmd
    {
        public int Id { get; set; }
        public string Recommendation { get; set; }
        public System.DateTime DateRec { get; set; }
        public bool IsDone { get; set; }
        public int InvItemId { get; set; }
        public int InvCarMntPriorityId { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
    
        public virtual InvItem InvItem { get; set; }
        public virtual InvCarMntPriority InvCarMntPriority { get; set; }
    }
}
