//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineReservation
    {
        public int Id { get; set; }
        public System.DateTime DtPosted { get; set; }
        public string ProductCode { get; set; }
        public System.DateTime DtStart { get; set; }
        public System.DateTime DtEnd { get; set; }
        public string Name { get; set; }
        public string ContactNum { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> PaymentAmt { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> DtPayment { get; set; }
        public string Remarks { get; set; }
    }
}
