//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLeadItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesLeadItems()
        {
            this.SalesLeadQuotedItems = new HashSet<SalesLeadQuotedItem>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> QuotedPrice { get; set; }
        public string Remarks { get; set; }
        public int SalesLeadId { get; set; }
        public int InvItemId { get; set; }
    
        public virtual SalesLead SalesLead { get; set; }
        public virtual InvItem InvItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesLeadQuotedItem> SalesLeadQuotedItems { get; set; }
    }
}
