//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesStatusRestriction
    {
        public int Id { get; set; }
        public int SalesStatusAllowedUsersId { get; set; }
        public int SalesStatusCodeId { get; set; }
    
        public virtual SalesStatusAllowedUsers SalesStatusAllowedUser { get; set; }
        public virtual SalesStatusCode SalesStatusCode { get; set; }
    }
}
