//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDocument
    {
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public int SupDocumentId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual SupDocument SupDocument { get; set; }
    }
}
