//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierActivity
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime DtActivity { get; set; }
        public string Assigned { get; set; }
        public string Remarks { get; set; }
        public int SupplierId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Type { get; set; }
        public string ActivityType { get; set; }
        public int SupplierActStatusId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual SupplierActStatus SupplierActStatu { get; set; }
    }
}
